### ISSUE TITLE
FuryWatch not working

### ISSUE THREAD

**Issue by JanaMSol** [The-Sickness/FuryWatch#1]
FuryWatch is not working for me. The button for the addon is not present, so I cannot adjust anything.

**Comment by The-Sickness** [comment]
Can you be more specific? I just reinstalled it and it fine. Did you download it from here on GitHub, or on Curseforge? Because if you downloaded it from my repo you must change the name.

**Comment by JanaMSol** [comment]
Hi :) I download it from curseforge. I can't change any settings because there is no furywatch in addons where you go to chang settings. Is there a command that I can use. But the addon is loaded
[furywatch.docx](https://github.com/user-attachments/files/16741013/furywatch.docx)
Hope you under stand this <3

**Comment by The-Sickness** [comment]
That is strange. I suggest to delete it from your addon folder and download it again. Grab the newest one. I just updated it yesterday.

**Comment by JanaMSol** [comment]
Sorry for not replying until now :) but the addon works but I can't configure in any way.

**Comment by The-Sickness** [comment]
So did you download a fresh copy? I just updated it on Curse yesterday.

**Comment by JanaMSol** [comment]
Yes I did :) but still nothing. Is there command that I can write in chat?

**Comment by The-Sickness** [comment]
No, there is no command. I would suggest deleting it again. Re-download it. And disable ALL your addons but FuryWatch. Then try it. Something or some addon is messing it up.

**Comment by JanaMSol** [comment]
ok thx :)

**Comment by JanaMSol** [comment]
Nob sorry didn't work, I guess this addon is not for me :'( but thx anyway

**Comment by The-Sickness** [comment]
Sorry to hear that man.
