### ISSUE TITLE
TWW - Cannot find a library instance of "AceConfigRegistry-3.0"

### ISSUE THREAD

**Issue by ronpritch1** [The-Sickness/FuryWatch#2]
After continued issues I blew away all addons and just installed FuryWatch and keep getting the following error on login.
------------
Message: ...ddOns/FuryWatch/Libs/AceConfig-3.0/AceConfig-3.0.lua:15: Cannot find a library instance of "AceConfigRegistry-3.0".
Time: Sun Oct  6 03:13:40 2024
Count: 1
Stack: ...ddOns/FuryWatch/Libs/AceConfig-3.0/AceConfig-3.0.lua:15: Cannot find a library instance of "AceConfigRegistry-3.0".
[string "@Interface/AddOns/FuryWatch/Libs/LibStub/LibStub.lua"]:23: in function `LibStub'
[string "@Interface/AddOns/FuryWatch/Libs/AceConfig-3.0/AceConfig-3.0.lua"]:15: in main chunk

Locals: self = <table> {
 minors = <table> {
 }
 minor = 2
 libs = <table> {
 }
}
major = "AceConfigRegistry-3.0"
silent = nil

**Comment by The-Sickness** [comment]
10-4. I will check it out and see what the issue is.
EDIT: It's all fixed and update is on Curse.
